version: '3.9'
services:
  debugger:
    image: ubuntu
    volumes:
      - redis_data:/userdata
    entrypoint: ['tail', '-f', '/dev/null']
    deploy:
      replicas: 1

  tor:
    image: debridmediamanager/tor:latest
    deploy:
      replicas: 1

  web:
    image: debridmediamanager/debrid-media-manager:latest
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.local
    depends_on:
      - tor
      - redis-sentinel
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis-master:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=REDACTED_REDIS_PASSWORD
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 6379
    deploy:
      replicas: 1

  redis-slave:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_PASSWORD=REDACTED_REDIS_PASSWORD
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=REDACTED_REDIS_PASSWORD
    depends_on:
      - redis-master
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 6379
    deploy:
      replicas: 1

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=REDACTED_REDIS_PASSWORD
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - 26379
    deploy:
      replicas: 1

volumes:
  redis_data:
    external: true
